version: '3.8'

services:
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-service
    ports:
      - "5000"
    restart: always
    environment:
      - ENV=production

  nginx:
    image: nginx:latest
    container_name: ai-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - ai-service
    restart: always
